//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BespokedBikes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Discount
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public System.DateTime Begin_Date { get; set; }
        public System.DateTime End_Date { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = false, DataFormatString = "{0:P0}")]
        public Nullable<decimal> Discount_Percentage { get; set; }
    
        public virtual Product Product1 { get; set; }
    }
}
