//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BespokedBikes.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Sale
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public int Salesperson { get; set; }
        public int Customer { get; set; }
        [DisplayName("Sales Date")]
        public System.DateTime Sales_Date { get; set; }
    
        public virtual Customer Customer1 { get; set; }
        public virtual Product Product1 { get; set; }
        public virtual Salesperson Salesperson1 { get; set; }
    }
}
